### ISSUE TITLE
PDF creation with PyPDF2 - Loop to create several files

### ISSUE THREAD

**Issue by FranRomerovedat** [FranRomerovedat/pdfcreator#1]
Hi,

I am very new at Python, so apologies in advance in something doesn't make sense

I am trying to create a pdf file (finalfile.pdf) where I want to add a list of names, one each time. I want to get 3 final files (one per name of the list (name1, name2, name3).
Thanks for your help!

from PyPDF2 import PdfFileWriter, PdfFileReader
import io
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter

names = ['name1', 'name2', 'name3']

for name in names:
    packet = io.BytesIO()
    # create a new PDF with Reportlab
    can = canvas.Canvas(packet, pagesize=letter)
    can.setFont("Helvetica", 25)
    can.setFillColorRGB(255, 255, 255)
    can.drawString(650, 118, name)
    can.save()

#move to the beginning of the StringIO buffer
packet.seek(0)
new_pdf = PdfFileReader(packet)

# read your existing PDF
existing_pdf = PdfFileReader(open('/Users/file.pdf', "rb"))
output = PdfFileWriter()

# add the "watermark" (which is the new pdf) on the existing page
page = existing_pdf.getPage(0)
page.mergePage(new_pdf.getPage(0))
output.addPage(page)

# finally, write "output" to a real file
outputStream = open("finalfile.pdf", "wb")
output.write(outputStream)
outputStream.close()

**Comment by SaxenaKartik** [comment]
I am able to run the given code and I would love to contribute on this issue 
I am not sure if I am getting a proper output though 
Could you provide me sample `file.pdf` and `finalfile.pdf` files so that I am able to validate the code and help with the issue?

**Comment by FranRomerovedat** [comment]
Hello @SaxenaKartik, thanks for your help on this. attached you can see two pdf files you can 
[FinalFile.pdf](https://github.com/FranRomerovedat/pdfcreator/files/5418091/FinalFile.pdf)
[File.pdf](https://github.com/FranRomerovedat/pdfcreator/files/5418092/File.pdf)

**Comment by SaxenaKartik** [comment]
I think I have worked this out, kindly assign me the issue so that I can make a PR @FranRomerovedat 
I am able to create 3 separate PDFs (attached below)

What should be the final file names for each of these PDFs?

[name3finalfile.pdf](https://github.com/FranRomerovedat/pdfcreator/files/5424368/name3finalfile.pdf)
[name2finalfile.pdf](https://github.com/FranRomerovedat/pdfcreator/files/5424367/name2finalfile.pdf)
[name1finalfile.pdf](https://github.com/FranRomerovedat/pdfcreator/files/5424373/name1finalfile.pdf)
